import { useRouter } from "next/router";
import { useEffect, useState, useRef } from "react";
import { useSelector, useDispatch } from "react-redux";
import {
  selectPhotos,
  addPhoto,
  addProfile,
  selectProfile,
} from "../../features/userSlice";
import Head from "next/head";
import db from "../../config/firebase";
import Header from "../../components/Header";
import UserBio from "../../components/UserBio";
import UserPhoto from "../../components/UserPhoto";

function Profile({ bio, photos }) {
  const dispatch = useDispatch();
  const router = useRouter();
  const [userData, setUserData] = useState([]);
  const [photo, setPhoto] = useState([]);
  const photoCollecction = useSelector(selectPhotos);
  const userProfile = useSelector(selectProfile);

  useEffect(() => {
    if (router.query.id) {
      async function getPhotos() {
        const unsubscribe = db
          .collection("photos")
          .where("userId", "==", router.query.id)
          .onSnapshot((snapshot) =>
            setPhoto(snapshot.docs.map((doc) => doc.data()))
          );
        return unsubscribe;
      }
      getPhotos();
    }
  }, [router.query.id]);

  useEffect(() => {
    if (router.query.id) {
      async function getUserData() {
        const unsubscribe = db
          .collection("users")
          .doc(router.query.id)
          .onSnapshot((snapshot) => setUserData(snapshot.data()));

        return unsubscribe;
      }
      getUserData();
    }
  }, [router.query.id]);

  useEffect(() => {
    async function addVisitProfile() {
      await dispatch(
        addProfile({
          profileDocId: userData?.userId,
          profileUsername: userData?.username,
          image: userData?.photoURL,
          profileUserId: userData?.userId,
          fullName: userData?.fullName,
          photosCount: photoCollecction?.length,
          followers: userData?.followers,
          followersCount: userData?.followers?.length,
          following: userData?.following,
          followingCount: userData?.following?.length,
          bios: userData?.bios,
          email: userData?.email,
        })
      );
    }
    addVisitProfile();
  });

  const showBio = () => {
    return JSON.parse(bio).map((userData) => (
      <UserBio
        key={userData?.id}
        profileDocId={userData?.userId}
        profileUsername={userData?.username}
        image={userData?.photoURL}
        profileUserId={userData?.userId}
        fullName={userData?.fullName}
        photosCount={photoCollecction?.length}
        followers={userData?.followers}
        following={userData?.following}
        bios={userData?.bios}
        profileEmail={userData?.email}
      />
    ));
  };

  const ShowPhoto = () => {
    return JSON.parse(photos).map((photo) => (
      <UserPhoto key={photo.id} photo={photo} />
    ));
  };

  useEffect(() => {
    dispatch(addPhoto(photo));
  });

  return (
    <div className="w-full">
      <Head>
        <title>{userData.username} Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {bio ? (
        <main>
          {userProfile ? showBio() : null}
          <div className="px-5 my-10 gap-8 sm:grid md:grid-cols-2 xl:grid-cols-3 3xl:flex flex-wrap items-center justify-center">
            {ShowPhoto()}
          </div>
        </main>
      ) : null}
    </div>
  );
}

export default Profile;

export async function getServerSideProps(context) {
  const ref = await db
    .collection("users")
    .where("userId", "==", context.query.id)
    .get();

  const photoRef = await db
    .collection("photos")
    .where("userId", "==", context.query.id)
    .get();

  const bio = ref.docs.map((item) => ({
    ...item.data(),
    docId: item.id,
  }));

  const photos = photoRef.docs.map((photo) => ({
    ...photo.data(),
    docId: photo.id,
  }));

  return {
    props: {
      bio: JSON.stringify(bio),
      photos: JSON.stringify(photos),
    },
  };
}
