import React from "react";
import dynamic from "next/dynamic";
import Head from "next/head";

import Skeleton from "react-loading-skeleton";
import db, { auth } from "../config/firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import { useDocument } from "react-firebase-hooks/firestore";
const Header = dynamic(() => import("../components/Header/Header"));
const User = dynamic(() => import("../components/Feeds/Sidebar/User"));
const Suggestion = dynamic(() =>
  import("../components/Feeds/Sidebar/Suggestion")
);
const Follower = dynamic(() => import("../components/Follower/Follower"));
const MenuModal = dynamic(() => import("../components/Modal/MenuModal"));

import { selectMenuModalIsOpen } from "../features/modalSlice";
import { useSelector } from "react-redux";

function Followerlist() {
  const menuModal = useSelector(selectMenuModalIsOpen);

  const [user] = useAuthState(auth);
  const [userData, loading] = useDocument(
    user && db.collection("users").doc(user?.uid)
  );
  if (loading) return <Skeleton count={1} height={61} />;

  return (
    <div>
      <Head>
        <title>ZH Instagram || Follower List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="grid px-8">
        <div>
          <User
            username={userData?.data().username}
            fullName={userData?.data().fullName}
            image={userData?.data().photoURL}
            uid={userData?.data().userId}
          />
          <Suggestion
            userId={userData?.data().userId}
            following={userData?.data().following}
            loggedInUserDocId={userData?.id}
          />
          <div className="mt-10 border-gray-300 border-t-2 py-4">
            <Follower
              username={userData?.data().username}
              userId={userData?.data().userId}
              follower={userData?.data().follower}
              loggedInUserDocId={userData?.id}
              following={userData?.data().following}
            />
          </div>
        </div>
      </div>
      {menuModal && <MenuModal />}
    </div>
  );
}

export default Followerlist;
