import { useEffect, useState } from "react";
import Head from "next/head";
//components
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Timeline from "../components/Timeline";
import Loading from "../components/loading";
//config
import db, { auth } from "../config/firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import { useDocument } from "react-firebase-hooks/firestore";
//redux
import { useDispatch } from "react-redux";
import { login } from "../features/userSlice";

export default function Home() {
  const dispatch = useDispatch();
  const [user] = useAuthState(auth);
  const userDataRef = db.collection("users").doc(user?.uid);
  const [userData, loading] = useDocument(userDataRef);

  const email = userData?.data().email;
  const profileUsernam = userData?.data().username;
  const profileDocId = userData?.data().userId;
  const image = userData?.data().photoURL;
  const profileUserId = userData?.data().userId;
  const fullName = userData?.data().fullName;

  useEffect(() => {
    if (!loading) {
      async function updateUserData() {
        await dispatch(
          login({
            profileDocId: profileDocId,
            email: email,
            profileUsername: profileUsernam,
            image: image,
            profileUserId: profileUserId,
            fullName: fullName,
          })
        );
      }
      updateUserData();
    }
  }, [loading]);

  return (
    <div>
      <Head>
        <title>ZH Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="grid grid-cols-3 gap-4 justify-between mx-auto max-w-screen-lg">
        <Timeline />
        <Sidebar />
      </main>
    </div>
  );
}
