import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
//config
import { auth } from "../config/firebase";
//components
import Header from "../components/Header";

function Login() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const isInvalid = password === "" || email === "";
  const [emailError, setEmailError] = useState(null);
  const [passwordError, setPasswordError] = useState(null);

  const login = (event) => {
    event.preventDefault();

    //reset errors
    setEmailError(null);
    setPasswordError(null);

    //validation
    if (email.length == 0) {
      setEmailError("Invalid Email");
      return setEmail("");
    }
    if (
      !/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/.test(
        email
      )
    ) {
      setEmailError("invalid email");
      return setEmail("");
    }
    if (password.length == 0) {
      setPasswordError("Too short");
      return setPassword("");
    }

    auth
      .signInWithEmailAndPassword(email, password)
      .then((auth) => {
        //login success, redirect to homepage
        router.push("/");
      })
      .catch((e) => alert(e.message))
      .then(() => {
        setEmail("");
        setPassword("");
      });
  };

  return (
    <div className="container h-screen ">
      <Head>
        <title>ZH Instagram - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex mx-auto max-w-screen-md items-center p-4">
        <div className="hidden lg:flex w-3/5">
          <img
            src="/images/iphone-with-profile.jpg"
            alt="iphone-with-instagram-app"
          />
        </div>
        <div className="flex flex-col w-full lg:w-2/5">
          <h1 className="flex justify-center w-full">
            <img src="/images/logo.png" alt="logo" />
          </h1>
          {error && <p className="mb-4 text-xs text-red-400">{error}</p>}
          <form onSubmit={login} method="POST">
            <input
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              arial-label="Enter your email"
              placeholder={emailError === null ? "Email" : emailError}
              className={`text-sm text-gray-500 w-full pr-3 py-5 px-4 border border-gray-primary rounded mb-2 focus-within:shadow-lg outline-none
            ${emailError !== null && "border-2 border-red-500"}`}
            />
            <input
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              arial-label="Enter your password"
              placeholder={passwordError === null ? "Password" : passwordError}
              className={`text-sm text-gray-500 w-full pr-3 py-5 px-4 border border-gray-primary rounded mb-2 focus-within:shadow-lg outline-none
            ${passwordError !== null && "border-2 border-red-500"}`}
            />
            <button
              onClick={login}
              disabled={isInvalid}
              type="submit"
              className={`bg-blue-500 text-white w-full rounded h-10 lg:h-8 font-bold hover:shadow-xl ${
                isInvalid && "opacity-50 "
              }`}
            >
              Login
            </button>
          </form>
          <div className="flex justify-center flex-col w-full bg-white p-4 border border-gray-100">
            <p>
              Dont have account?
              <span
                onClick={() => router.push("/register")}
                className="ml-1 hover:underline cursor-pointer"
              >
                Sign Up
              </span>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}

export default Login;
