import { useRef, useState, useEffect } from "react";
import db, { storage } from "../config/firebase";
import { BsFillImageFill } from "react-icons/bs";
import Header from "../components/Header/Header";

import { AiFillInstagram } from "react-icons/ai";
import firebase from "firebase";
import { useRouter } from "next/router";
import Head from "next/head";

import useAuth from "../hooks/useAuth";

function StoryUpload() {
  const { user } = useAuth();
  const [userData, setUserData] = useState([]);

  const inputRef = useRef(null);
  const imgPickerRef = useRef(null);
  const [imgToPost, setImgtoPost] = useState(null);
  const [haveImg, setHaveImg] = useState(false);
  const router = useRouter();

  useEffect(() => {
    if (user) {
      let unsubscribe;
      const fetchUSerData = () => {
        unsubscribe = db
          .collection("users")
          .doc(user?.uid)
          .get()
          .then((documentSnapshot) => {
            if (!documentSnapshot.exists) {
            } else {
              //console.log('User data: ', documentSnapshot.data());
              setUserData(documentSnapshot.data());
            }
          });
      };
      fetchUSerData();
      return unsubscribe;
    }
  }, [db, user]);

  const addImgtoPost = (e) => {
    const reader = new FileReader();
    setHaveImg(true);
    if (e.target.files[0]) {
      reader.readAsDataURL(e.target.files[0]);
    }

    reader.onload = (readerEvent) => {
      setImgtoPost(readerEvent.target.result);
    };
  };

  const removeImg = () => {
    setHaveImg(false);
    setImgtoPost(null);
  };
  const sendPost = (e) => {
    e.preventDefault();

    if (!user) return false;
    if (!haveImg) return false;

    db.collection("stories")
      .add({
        username: userData?.username,
        photoId: Date.now(),
        userId: user?.uid,
        caption: inputRef.current.value,
        likes: [],
        comments: [],
        timestamp: firebase.firestore.FieldValue.serverTimestamp(),
      })
      .then((doc) => {
        if (imgToPost) {
          const uploadTask = storage
            .ref(`stories/${doc.id}`)
            .putString(imgToPost, "data_url");

          removeImg();

          uploadTask.on(
            "state_change",
            null,
            (error) => console.error(error),
            () => {
              storage
                .ref("stories")
                .child(doc.id)
                .getDownloadURL()
                .then((url) => {
                  db.collection("stories").doc(doc.id).set(
                    {
                      image: url,
                    },
                    {
                      merge: true,
                    }
                  );
                });
            }
          );
        }
      })
      .then(() => {
        router.push("/");
      });

    inputRef.current.value = "";
  };

  return (
    <>
      <Header userData={userData} />
      <div className="bg-white p-2 rounded-2xl shadow-md text-gray-500 font-medium mt-6">
        {imgToPost && (
          <div
            onClick={removeImg}
            className="flex flex-col items-center justify-center filter hover:brightness-110 transition duration-150 transform hover:scale-105 cursor-pointer"
          >
            <img className="h-60 w-60 object-contain" src={imgToPost} alt="" />
            <p className="text-xs text-red-500 text-center">Remove</p>
          </div>
        )}
        <Head>
          <title>{userData?.username} Stories Upload</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="flex space-x-4 items-center p-4">
          <img
            className="rounded-full h-20 w-20 "
            src={userData?.photoURL}
            layout="fixed"
            alt={userData?.username}
          />
          <form className="flex flex-1">
            <input
              ref={inputRef}
              className=" rounded-full h-12 bg-gray-100 flex-grow px-5 focus:outline-none"
              type="text"
              placeholder={`what's on your mind, ${userData?.username}`}
            />
            <button hidden onClick={sendPost}>
              Submit
            </button>
          </form>
        </div>
        <div className="px-10 flex items-center space-x-12 p-3 border-t overflow-x-scroll md:overflow-x-hidden">
          {haveImg && (
            <div className="inputIcon" onClick={sendPost}>
              <AiFillInstagram
                className={`h-8 w-8 text-pink-500 cursor-pointer opacity-50 ${
                  !imgPickerRef && "opacity-100"
                }`}
              />
              <p className="text-xs sm:text-sm lg:text-base">Upload</p>
            </div>
          )}

          <div
            className="inputIcon"
            onClick={() => imgPickerRef.current.click()}
          >
            <BsFillImageFill className="h-8 w-8 text-green-500 cursor-pointer" />
            <p className="text-xs sm:text-sm lg:text-base">Photo/Video</p>
            <input
              ref={imgPickerRef}
              type="file"
              hidden
              onChange={addImgtoPost}
            />
          </div>
        </div>
      </div>
    </>
  );
}

export default StoryUpload;
